// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace datatablesProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("datatablesProject.Models.CariHesaplar", b =>
                {
                    b.Property<int>("HesapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HesapID"));

                    b.Property<string>("AdresIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariHesapAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariILce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariTelNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cariVergiNO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HesapID");

                    b.ToTable("CariHesaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
